language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - '8.11.3'

install:
  - npm install

# before_script:
#   - npm test

script:
  - npm run build:production

after_success:
  - npm run travis-deploy-once "npm run semantic-release -- --debug"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
